### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by ghost** [jessica-suen/prj-rev-bwfs-dasmoto#1]
https://github.com/jessica-suen/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L12-L17

Good job putting each "item" section in its own div and leaving a line between each section. This makes your code very easy to read through.

Consider giving each div the shared class name "item". This makes it easier to apply shared styles (since each item section is mostly styled the same except for a single element). Then you can give the child h2 element the ID "brushes" or "frames" if you'd like.

**Comment by jessica-suen** [comment]
<img width="673" alt="screen shot 2017-07-02 at 3 29 07 pm" src="https://user-images.githubusercontent.com/29494819/27773958-3920f76c-5f3b-11e7-916a-62fecb18a7e8.png">

Thanks Steve! I imagine that'd be a much better way to organize when you have a lot of content going on rather than in just the specs of this assignment.
